apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  namespace: development
  labels:
    type: front-end
spec: # this spec belongs to the replicaset
  template:
    metadata:
      name: my-pod
      namespace: development
      labels:
        type: front-end
    spec: # this spec belongs to the pod
      containers:
      - name: busy-box
        image: busybox
  replicas: 3
  selector:
    matchLabels:
      type: front-end # this label is to tag the pods. NOTE- in replica set we can crteate replicas of pods without defind the pod template inside it, for that purpose we need selector here




